name: NetDevOps CD - Despliegue Continuo en EVE-NG

on:
  push:
    branches: [ main ]

jobs:
  despliegue-produccion:
    name: 🚀 Despliegue Automatizado en Routers EVE-NG
    runs-on: self-hosted
    env:
      ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - name: Descargar la versión oficial aprobada del código
        uses: actions/checkout@v4

      - name: Verificar conectividad local con servidor EVE-NG
        run: |
          echo "🔌 Probando ping hacia la red física de laboratorios..."
          ping -c 2 192.168.85.130 || echo "⚠️ Alerta: EVE-NG no responde al ping, pero se intentará la conexión."

      - name: Desplegar Fase 1 - Interfaces y Enlaces Core
        run: |
          cd ansible
          ansible-playbook -i inventario.ini playbook_1_ips.yml

      - name: Desplegar Fase 2 - Enrutamiento OSPF
        run: |
          cd ansible
          ansible-playbook -i inventario.ini playbook_2_ospf.yml

      - name: Desplegar Fase 3 - Protocolo MPLS LDP
        run: |
          cd ansible
          ansible-playbook -i inventario.ini playbook_3_ldp.yml

      - name: Desplegar Fase 4 - Sesiones MP-BGP
        run: |
          cd ansible
          ansible-playbook -i inventario.ini playbook_4_bgp.yml

      - name: Desplegar Fase 5 - VRFs de Clientes
        run: |
          cd ansible
          ansible-playbook -i inventario.ini playbook_5_vrf.yml
